---
default_install_hook_types:
    - commit-msg
    - prepare-commit-msg
    - pre-commit
    - pre-merge-commit
    - pre-push
    - pre-rebase
    - post-checkout
    - post-commit
    - post-merge
    - post-rewrite

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

          # Json
          - id: check-json

          # Python
          - id: check-ast # Check whether files parse as valid python.
          - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
          - id: check-docstring-first
          - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
          - id: name-tests-test # Assert that files in tests/ end in _test.py, or optionally test*.py
          - id: requirements-txt-fixer

    # General

    - repo: https://github.com/sirosen/texthooks
      rev: 0.6.8
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            stages: [pre-commit]

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint

    # Python

    - repo: https://github.com/econchick/interrogate
      rev: 1.7.0
      hooks:
          - id: interrogate
            args:
                - --verbose

    - repo: https://github.com/ikamensh/flynt/
      rev: 1.0.1
      hooks:
          - id: flynt

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.19.1
      hooks:
          - id: blacken-docs

    - repo: https://github.com/MarcoGorelli/auto-walrus
      rev: 0.3.4
      hooks:
          - id: auto-walrus

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
            args:
                - --py36-plus

    - repo: https://github.com/PyCQA/bandit
      rev: 1.8.2
      hooks:
          - id: bandit

    - repo: https://github.com/asottile/dead
      rev: v2.1.0
      hooks:
          - id: dead

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.9.6"
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
            types_or: [python, pyi, jupyter] # Run on notebooks too.
          - id: ruff-format
            types_or: [python, pyi, jupyter] # Run on notebooks too.

    - repo: https://github.com/hadialqattan/pycln
      rev: v2.5.0
      hooks:
          - id: pycln

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-blanket-type-ignore
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal
          - id: text-unicode-replacement-char

    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
          - id: check-poetry # Validates the structure of the pyproject.toml file.

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # SQL

    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 3.3.1
      hooks:
          - id: sqlfluff-lint
          # For dbt projects, this installs the dbt "extras".
          # You will need to select the relevant dbt adapter for your dialect
          # (https://docs.getdbt.com/docs/available-adapters):
          # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
          - id: sqlfluff-fix
          # Arbitrary arguments to show an example
          # args: [--rules, "L003,L014"]
          # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']

    # Mixed

    - repo: https://github.com/kraymer/cesar
      rev: v1.0.0
      hooks:
          - id: cesar

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: script-must-not-have-extension

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.31.1
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.23.3
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
          - id: actionlint

    - repo: https://github.com/MarcoGorelli/cython-lint
      rev: v0.16.6
      hooks:
          - id: cython-lint

    - repo: https://github.com/lycheeverse/lychee.git
      rev: lychee-v0.18.1
      hooks:
          - id: lychee
          # Optionally include additional CLI arguments
          # args: ["--no-progress", "--exclude", "file://"]
