---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

          # Json
          - id: check-json

          # Python
          - id: check-ast # Check whether files parse as valid python.
          - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
          - id: check-docstring-first
          - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
          - id: name-tests-test # Assert that files in tests/ end in _test.py, or optionally test*.py
          - id: requirements-txt-fixer

    # General

    - repo: https://github.com/sirosen/texthooks
      rev: 0.4.0
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.2
      hooks:
          - id: prettier
            stages: [commit]

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0
      hooks:
          - id: gitlint

    # Markdown

    - repo: https://github.com/tcort/markdown-link-check
      rev: v3.10.3
      hooks:
          - id: markdown-link-check
            args:
                - --config
                - .markdown-link-check.json

    # Python

    - repo: https://github.com/econchick/interrogate
      rev: 1.5.0
      hooks:
          - id: interrogate

    - repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.1
      hooks:
          - id: darglint

    - repo: https://github.com/ikamensh/flynt/
      rev: 1.0.1
      hooks:
          - id: flynt

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.16.0
      hooks:
          - id: blacken-docs

    - repo: https://github.com/PyCQA/docformatter
      rev: v1.5.0
      hooks:
          - id: docformatter
            args: ['--in-place', '--config', './pyproject.toml']

    - repo: https://github.com/HunterMcGushion/docstr_coverage
      rev: v2.2.0
      hooks:
          - id: docstr-coverage
            args: ['--verbose', '4', '.']
            always_run: false

    - repo: https://github.com/MarcoGorelli/auto-walrus
      rev: v0.2.1
      hooks:
          - id: auto-walrus

    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.326
      hooks:
          - id: pyright

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
            args:
                - --py36-plus

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.4
      hooks:
          - id: bandit

    - repo: https://github.com/asottile/dead
      rev: v1.5.0
      hooks:
          - id: dead

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black-jupyter

    - repo: https://github.com/hadialqattan/pycln
      rev: v2.2.2
      hooks:
          - id: pycln

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-blanket-type-ignore
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal
          - id: text-unicode-replacement-char

    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
          - id: check-poetry # Validates the structure of the pyproject.toml file.

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.263'
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # SQL

    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 1.3.2
      hooks:
          - id: sqlfluff-lint
          # For dbt projects, this installs the dbt "extras".
          # You will need to select the relevant dbt adapter for your dialect
          # (https://docs.getdbt.com/docs/available-adapters):
          # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
          - id: sqlfluff-fix
          # Arbitrary arguments to show an example
          # args: [--rules, "L003,L014"]
          # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']

    # Mixed

    - repo: https://github.com/kraymer/cesar
      rev: v1.0.0
      hooks:
          - id: cesar

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: script-must-not-have-extension

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.4
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.26.3
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.18.0
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.6.25
      hooks:
          - id: actionlint

    - repo: https://github.com/MarcoGorelli/cython-lint
      rev: v0.1.10
      hooks:
          - id: cython-lint

    - repo: https://github.com/RyoWakabayashi/pre-commit-mirrors-textlint
      rev: v12.2.1
      hooks:
          - id: textlint
            additional_dependencies:
                [
                    'textlint',
                    'textlint-plugin-latex2e',
                    'textlint-filter-rule-comments',
                    'textlint-rule-alex',
                    'textlint-rule-apostrophe',
                    'textlint-rule-common-misspellings',
                    'textlint-rule-diacritics',
                    'textlint-rule-doubled-spaces',
                    'textlint-rule-editorconfig',
                    'textlint-rule-en-capitalization',
                    'textlint-rule-en-spell',
                    'textlint-rule-max-number-of-lines',
                    'textlint-rule-no-dead-link',
                    'textlint-rule-no-empty-section',
                    'textlint-rule-no-start-duplicated-conjunction',
                    'textlint-rule-no-todo',
                    'textlint-rule-stop-words',
                    'textlint-rule-terminology',
                    'textlint-rule-write-good',
                    'textlint-rule-unexpanded-acronym',
                    '@textlint-rule/textlint-rule-no-duplicate-abbr',
                    '@textlint-rule/textlint-rule-no-invalid-control-character',
                ]

    - repo: https://github.com/streetsidesoftware/cspell-cli
      rev: v6.12.0
      hooks:
          - id: cspell

    - repo: https://github.com/bridgecrewio/checkov/
      rev: 2.1.273
      hooks:
          - id: checkov
